# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
cache: packages
r:
    - bioc-devel
warning_are_errors: true

r_packages:
    - covr
bioc_packages:
    - BiocCheck

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
