{
    "comment": false,
    "coverage": {
        "status": {
            "patch": {
                "default": {
                    "target": "auto",
                    "threshold": 1,
                    "informational": true
                }
            },
            "project": {
                "default": {
                    "target": "auto",
                    "threshold": 1,
                    "informational": true
                }
            }
        }
    }
}
